[package]
name = "antigen-shambler"
version = "0.1.0"
edition = "2021"

[dependencies]
legion = "0.4.0"

antigen-core = { path = "../antigen-core" }
antigen-fs = { path = "../antigen-fs" }
shambler = { path = "../../../sif/crates/shambler" }
